### ISSUE TITLE
Homepage-Text-Linked paragraph text

### ISSUE THREAD

**Issue by BenhamL** [oakwoodgates/happyhour#20]
![linked paragraph text](https://cloud.githubusercontent.com/assets/12160457/10029472/ad2ca1d2-6137-11e5-8561-c490811ed8b7.png)

**Comment by oakwoodgates** [comment]
Would it be better if the links were underlined?

**Comment by BenhamL** [comment]
I think we tried underlined before and it was still too light to see. Is this a color issue? Text issue?

**Comment by BenhamL** [comment]
this is fixed
