### ISSUE TITLE
Tulsa page - Food/Drink text area

### ISSUE THREAD

**Issue by BenhamL** [oakwoodgates/happyhour#31]
Please change the text here:
![screen shot 2015-10-13 at 10 41 39 am](https://cloud.githubusercontent.com/assets/12160457/10459833/0b00ae60-7197-11e5-95c6-d8698ab9e01e.png)

to say 'Cirtus Mule' for the drink. and link to this post now: http://nighttrips.com/Tulsa/drink-recipes/citrus-mule

**Comment by BenhamL** [comment]
Citrus Mule ------ NOT Cirtus. Sorry

**Comment by oakwoodgates** [comment]
Just for reference, that's wp-admin->Site Options..."Featured Blog Post"
