### ISSUE TITLE
Missing Links in footer

### ISSUE THREAD

**Issue by BenhamL** [oakwoodgates/happyhour#32]
![screen shot 2015-10-13 at 1 53 03 pm](https://cloud.githubusercontent.com/assets/12160457/10464921/df17f9be-71b1-11e5-9b20-2b71eff45131.png)

**Comment by BenhamL** [comment]
both okc and tulsa sites

**Comment by BenhamL** [comment]
@oakwoodgates and this too?

**Comment by oakwoodgates** [comment]
fixed. For future reference those are in wp-admin->Appearance->Menu. There are two menus, one for the header and one for the footer.
