### ISSUE TITLE
Blank Table Tent Area on OKC site

### ISSUE THREAD

**Issue by BenhamL** [oakwoodgates/happyhour#37]
On Tulsa's site here, there is a pluxh graphic:
![screen shot 2015-10-13 at 3 24 07 pm](https://cloud.githubusercontent.com/assets/12160457/10467325/a5603904-71be-11e5-8ec5-935051c7c39b.png)
What are we doing for OKC space here: 
![screen shot 2015-10-13 at 3 24 23 pm](https://cloud.githubusercontent.com/assets/12160457/10467337/b4693306-71be-11e5-962a-7798ee3a35f0.png)

Where can I put that graphic on the backside? Can we fill the void with something else?

**Comment by BenhamL** [comment]
on the single event pages

**Comment by oakwoodgates** [comment]
wp-admin->Site Options...."Pluxh Callout Image" will output an image that links to your VIP page. That's actually a lot of places on the site. Should it be different for OKC?

**Comment by BenhamL** [comment]
@oakwoodgates i uploaded one for OKC into the Pluxh Callout area. Im closing this out.
