### ISSUE TITLE
Missing food/drink picture gallery - OKC homepage

### ISSUE THREAD

**Issue by BenhamL** [oakwoodgates/happyhour#38]
![screen shot 2015-10-13 at 3 39 35 pm](https://cloud.githubusercontent.com/assets/12160457/10467700/df25f244-71c0-11e5-8f5f-29546573d2b9.png)

**Comment by BenhamL** [comment]
http://nighttrips.com/OKC/

**Comment by BenhamL** [comment]
@oakwoodgates here they are: _id=1984
1990
1981
1955
1972

They were chosen so it could be identical to Tulsa's. 2 vertical, 3 horizontal.

**Comment by oakwoodgates** [comment]
adding for reference
1977
1982
1985
