### ISSUE TITLE
change options under social on homepage

### ISSUE THREAD

**Issue by BenhamL** [oakwoodgates/happyhour#41]
Where can I change the youtube video and twitter post that is under the Social area on homepage? They're different than the ones in the site options.

Right now the video is wrong on the OKC page down there

@oakwoodgates

**Comment by oakwoodgates** [comment]
The video at the bottom is the latest from the "BoobTube"

**Comment by oakwoodgates** [comment]
That's where the twitter tweet is though - http://nighttrips.com/Tulsa/wp-admin/admin.php?page=happyhour_options
