### ISSUE TITLE
Images optimized

### ISSUE THREAD

**Issue by oakwoodgates** [oakwoodgates/happyhour#42]
I would consider it a priority to get the images optimized. The page load times are crazy slow (especially on tulsa homepage) and that's mostly why.

Keep in mind (for tiled gallery images):
- Resize - I would recommend 1200-1800px maximum wide (I'd say 800px max for vertical images)
- Compress - the image quality is super high, so reducing/compressing that down should be just fine and save a ton. 60% or so should be good.
- Rename - since they'll need to be re-added, I'd say rename the image file from names like 8843.jpg to cheeseburger-and-beer.jpg or tulsa-gentlemens-club-vip.jpg or whatever

I just thought I'd put this here as a reminder, but feel free to close it out. I would definitely consider this a major priority though, and this is a service I can offer if you don't have the time.

**Comment by BenhamL** [comment]
Yes, I would like to move forward with you changing the size of the images. 

I have a question on renaming though. I renamed every image that is on there now, so where is the number coming from? The numbers i sent you for images were ID numbers. are you saing to change the ID number? 

Can you please give me a cost first?
