### ISSUE TITLE
Form from join our team page is not working

### ISSUE THREAD

**Issue by BenhamL** [oakwoodgates/happyhour#43]
it is only sending me the name, email and phone number. There is a ( \* ) in the html on those two sections but no the others. Is the html not pulling the info for the email send out to us? 

See below: 

<div>Name (First and Last)<br />
    [text* name] </div>

<div>What position are you interested in?<br />
    [text position] </div>

<div>Tell us a little about yourself<br />
    [textarea about] </div>

<div>Please list any Skills or Experience<br />
    [textarea skills] </div>

<div>Tell us what your current availability is (days/times)<br />
    [text available] </div>

<div>What interests you in working for Night Trips?<br />
    [textarea interested] </div>

<div>How did you find out about us?<br />
    [text findout] </div>

<div>Your Email<br />
    [email* email] </div>

<div>Phone Number<br />
[tel* phone]
</div>

<div>[submit "Send"]</div>

**Comment by BenhamL** [comment]
@oakwoodgates is this possible with this plugin?

**Comment by BenhamL** [comment]
Can we send it to multiple email addresses? The GM's need to be receiving these not just the info@ email.

**Comment by oakwoodgates** [comment]
I fixed the issue, but I might have blacklisted my email or ip...can you test it out?

This is how you can add multiple emails - http://contactform7.com/adding-cc-bcc-and-other-mail-headers/

wp-admin->Contact->Contact Forms->(the form)->mail tab
